(test "doc on each builtin returns the canonical docstring"
  (assert/equal (doc +) "Add numbers.")
  (assert/equal (doc first) "Return the head of a pair.")
  (assert/equal (doc rest) "Return the tail of a pair.")
  (assert/equal (doc cons) "Create a pair from head and tail.")
  (assert/equal (doc list) "Build a proper list from items.")
  (assert/equal (doc array) "Build an array from items.")
  (assert/equal (doc object) "Build an object from alternating keyword keys and values.")
  (assert/equal (doc length) "Length of an array, string, list, or object.")
  (assert/equal (doc get) "Look up a key in an array or object.")
  (assert/equal (doc nil?) "True when the value is nil.")
  (assert/equal (doc null?) "True when the value is null.")
  (assert/equal (doc pair?) "True when the value is a pair.")
  (assert/equal (doc list?) "True when the value is nil or a proper list.")
  (assert/equal (doc array?) "True when the value is an array.")
  (assert/equal (doc symbol?) "True when the value is a symbol.")
  (assert/equal (doc =) "Deep equality; identity for callables.")
  (assert/equal (doc /=) "Logical inverse of =.")
  (assert/equal (doc print) "Canonical string representation of a value.")
  (assert/equal (doc parse) "Read an s-spec source string into a form.")
  (assert/equal (doc json/parse) "Parse strict JSON into an s-spec value.")
  (assert/equal (doc json/stringify) "Serialize a value to compact JSON.")
  (assert/equal (doc doc) "Get the docstring of a function, macro, or builtin.")
  (assert/equal (doc gensym) "Unique symbol.")
  (assert/equal (doc error) "Throw an error with the given message.")
  (assert/equal (doc bound?) "True when the given symbol is bound in the caller's env.")
  (assert/equal (doc macroexpand-1) "Expand the form once at the head, if it is a macro call.")
  (assert/equal (doc macroexpand) "Repeatedly macroexpand at the head until a fixpoint."))
